### ISSUE TITLE
Upgrading From 0.1.1 to 0.1.3 stops Background Play

### ISSUE THREAD

**Issue by singhdd93** [teodorpatras/Jukebox#10]
I am unable to play the music in background. Once the app is hidden by pressing home button the music stops with fade effect.

Reverting back to 0.1.1 fixes it.

**Comment by teodorpatras** [comment]
yes, because now, the call to `UIApplication.sharedApplication().beginReceivingRemoteControlEvents()` has been removed from inside Jukebox. Since you(the client) handle the remote events by overriding `remoteControlReceivedWithEvent(event:)`, it makes more sense to also call `beginReceivingRemoteControlEvents()`, checkout the Readme and the Example project for more info

**Comment by singhdd93** [comment]
I am keeping jukebox variable in singleton and then Access remote events from my custom Navigation Controller. 
I have the `UIApplication.sharedApplication().beginReceivingRemoteControlEvents()` in `viewDidLoad()` and have overriden `remoteControlReceivedWithEvent(event: UIEvent?)` but it still happens.

Thanks alot
